[project]
name = "EPRsim"
version = "0.1.1"
description = "A Python library for loading and simulating EPR spectra."
authors = [
	{name = "Stefan Rein", email = "stephan.rein@physchem.uni-freiburg.de"}
	{name = "Darien Morrow"}
	{name = "Liam Twomey"}
]
readme = "README.md"]
requires-python = ">=3.10"
keywords = ["photophysics","spectroscopy","science","electron","paramagnetic","resonance"]
license = "GPLv3"
classifiers = [
	"Programming Language :: Python :: 3"
]
dependencies = [
	'numpy',
	'scipy',
	'numba',
	'matplotlib',
	'pathlib',
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project.scripts]
